### ISSUE TITLE
Local private pub-server usage problem

### ISSUE THREAD

**Issue by ibabyblue** [dart-lang/pub_server#35]
I built the pub-server successfully on this machine, and then uploaded the private package successfully, but I am relying on this package in the project when the error is as follows:
![image](https://user-images.githubusercontent.com/13377910/55129479-39c6aa80-5152-11e9-8136-7ad0cb1a30ff.png)
Dependency settings are as follows：
![image](https://user-images.githubusercontent.com/13377910/55129559-80b4a000-5152-11e9-8b07-d87fb3900159.png)
Please help me to see what the problem is, thank you!

**Comment by jonasfj** [comment]
This package provides an abstraction and an example, we do support custom pub_server implementations. There are too many things that could be wrong for me to be helpful here.

In general I think it's better to build a custom pub-servers as separate project @v7lin has been doing this here: https://github.com/v7lin/simple_pub_server, that might be a good starting point too.

**Comment by ibabyblue** [comment]
@jonasfj i got it, thanks!
