### ISSUE TITLE
Pub Server Authentication For Private Pub Packages

### ISSUE THREAD

**Issue by noahbetzen-wk** [dart-lang/pub_server#39]
Currently in order to host proprietary pub packages on a private pub server, the server must be behind a VPN. There is no way to require authentication for package downloads. Maven, npm, and Go all have ways of putting packages behind authentication barriers.

I saw no existing issue discussing this, so I figured I'd make one to get it on the Dart team's radar.

**Comment by jonasfj** [comment]
Let's move this to https://github.com/dart-lang/pub/issues/1381 -- as you've already found it :)
