### ISSUE TITLE
Unable to push packet on pub.dartlang.org

### ISSUE THREAD

**Issue by ra1u** [dart-lang/pub_server#4]
Error message I get is

```
UnauthorizedAccess: Unauthorized user: luka.rahne@gmail.com is not allowed to upload versions to package redis..
```

While trying to upload redis package

https://pub.dartlang.org/packages/redis

I suspect it has something to do with email being capital. (at author -> luka.rahne@gmail.com but for uploaded is Luka.Rahne@gmail.com )

Since last upload I think I have replaced dart binaries so it is possible that bug is there (in pub)

**Comment by mkustermann** [comment]
Thank you for the report.

This is an issue for  https://github.com/dart-lang/pub-dartlang-dart and has been fixed.
