### ISSUE TITLE
After I executed "pub publish", the authorization was successful, but I always waited for timeout. May I ask why?

### ISSUE THREAD

**Issue by mr921112** [dart-lang/pub_server#43]
D:\pub_server\pub_server>pub publish
Publishing pub_server 0.1.6-dev to https://pub.flutter-io.cn:
|-- .gitignore
|-- .idea
|   |-- codeStyles
|   |   '-- Project.xml
|   |-- libraries
|   |   |-- Dart_Packages.xml
|   |   '-- Dart_SDK.xml
|   |-- misc.xml
|   |-- modules.xml
|   |-- pub_server.iml
|   |-- vcs.xml
|   '-- workspace.xml
|-- .travis.yml
|-- AUTHORS
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- analysis_options.yaml
|-- codereview.settings
|-- example
|   |-- example.dart
|   '-- src
|       '-- examples
|           |-- cow_repository.dart
|           |-- file_repository.dart
|           '-- http_proxy_repository.dart
|-- lib
|   |-- repository.dart
|   '-- shelf_pubserver.dart
|-- pubspec.yaml
'-- test
    '-- shelf_pubserver_test.dart
Suggestions:
* .\CHANGELOG.md doesn't mention current version (0.1.6-dev).
  Consider updating it with notes on this version prior to publication.

Package has 1 warning. Upload anyway (y/n)? y
Pub needs your authorization to upload packages on your behalf.
In a web browser, go to https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A61995&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
Then click "Allow access".

Waiting for your authorization...
Authorization received, processing...
It looks like accounts.google.com is having some trouble.
Pub will wait for a while before trying to connect again.
OS Error: 信号灯超时时间已到
, errno = 121, address = accounts.google.com, port = 62508

D:\pub_server\pub_server>pub publish
Publishing pub_server 0.1.6-dev to https://pub.flutter-io.cn:
|-- .gitignore
|-- .idea
|   |-- codeStyles
|   |   '-- Project.xml
|   |-- libraries
|   |   |-- Dart_Packages.xml
|   |   '-- Dart_SDK.xml
|   |-- misc.xml
|   |-- modules.xml
|   |-- pub_server.iml
|   |-- vcs.xml
|   '-- workspace.xml
|-- .travis.yml
|-- AUTHORS
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
|-- analysis_options.yaml
|-- codereview.settings
|-- example
|   |-- example.dart
|   '-- src
|       '-- examples
|           |-- cow_repository.dart
|           |-- file_repository.dart
|           '-- http_proxy_repository.dart
|-- lib
|   |-- repository.dart
|   '-- shelf_pubserver.dart
|-- pubspec.yaml
'-- test
    '-- shelf_pubserver_test.dart
Suggestions:
* .\CHANGELOG.md doesn't mention current version (0.1.6-dev).
  Consider updating it with notes on this version prior to publication.

Package has 1 warning. Upload anyway (y/n)? y
Pub needs your authorization to upload packages on your behalf.
In a web browser, go to https://accounts.google.com/o/oauth2/auth?access_type=offline&approval_prompt=force&response_type=code&client_id=818368855108-8grd2eg9tj9f38os6f1urbcvsq399u8n.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A63172&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email
Then click "Allow access".

Waiting for your authorization...
Authorization received, processing...
It looks like accounts.google.com is having some trouble.
Pub will wait for a while before trying to connect again.
OS Error: 信号灯超时时间已到
, errno = 121, address = accounts.google.com, port = 63891

**Comment by chenglu** [comment]
@mr921112
在发布 package 的时候，请将环境变量中的中国镜像设置删除，谢谢～
